// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDgDTLYZvMutm5qmbR7vtlZ8VeXPQYm9EE',
    appId: '1:924314436999:web:d3a45cd6d7dd34dd77ff22',
    messagingSenderId: '924314436999',
    projectId: 'diet-designer-c72db',
    authDomain: 'diet-designer-c72db.firebaseapp.com',
    storageBucket: 'diet-designer-c72db.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCq0_2h6il4QpELSndcD_PyLKLIQg3SPvs',
    appId: '1:924314436999:android:551dbd9010afea2a77ff22',
    messagingSenderId: '924314436999',
    projectId: 'diet-designer-c72db',
    storageBucket: 'diet-designer-c72db.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDtsGa7Y8e4xXbo7QZtmGHMwBmrLpCkm8M',
    appId: '1:924314436999:ios:158a5dc907eba1bb77ff22',
    messagingSenderId: '924314436999',
    projectId: 'diet-designer-c72db',
    storageBucket: 'diet-designer-c72db.appspot.com',
    iosClientId: '924314436999-cmeuft8h3auars30ju81f7c1kstcp9s1.apps.googleusercontent.com',
    iosBundleId: 'com.example.dietDesigner',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDtsGa7Y8e4xXbo7QZtmGHMwBmrLpCkm8M',
    appId: '1:924314436999:ios:158a5dc907eba1bb77ff22',
    messagingSenderId: '924314436999',
    projectId: 'diet-designer-c72db',
    storageBucket: 'diet-designer-c72db.appspot.com',
    iosClientId: '924314436999-cmeuft8h3auars30ju81f7c1kstcp9s1.apps.googleusercontent.com',
    iosBundleId: 'com.example.dietDesigner',
  );
}
